server:
  port: 8080

# Product data configuration
product:
  data:
    json-file: classpath:products.json

# OpenAI Configuration (optional - for AI-powered product generation)
openai:
  api:
    key: ${OPENAI_API_KEY:demo-key}

# Jackson configuration for proper date/time serialization
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss
